In [1]:
import numpy as np
A = np.array([[1,3,-2],[2,4,-1],[3,-6,8]])
B = np.array([[2,-3,4],[-1,-2,1],[4,-5,7]])
C = np.array([[-2,1,-6],[4,-3,9]])
D = np.array([[2,8,2],[-4,5,6],[7,-3,1]])
print(B)
print(C)

[[ 2 -3  4]
 [-1 -2  1]
 [ 4 -5  7]]
[[-2  1 -6]
 [ 4 -3  9]]


In [2]:
# Cara buat matrix dengan cepat menggunakan bilangan yang random

#A = np.random.randint(10,size=(3,3))
#print(A)

[[0 6 8]
 [1 7 2]
 [4 5 3]]


# **Operasi-operasi Matrik**
1. Matriks dalam bentuk apapun dapat dikalikan dengan skalar *c, d*.

In [3]:
c = 2
d = 4
e = c + d
G = (c+d)*A
H = (c*A) + (d*A)
print('e =', e)
print('G =', G)
print('H =', H)

e = 6
G = [[ 0 36 48]
 [ 6 42 12]
 [24 30 18]]
H = [[ 0 36 48]
 [ 6 42 12]
 [24 30 18]]


2. Matriks yang ukurannya sama bisa dijumlahkan. Hasilnya adalah semua elemen yang bersesuaian dan ditambah dalam bentuk.

In [4]:
K = A + B
#L = A + C
print('K =', K)
#print('L =', L)

K = [[ 2  3 12]
 [ 0  5  3]
 [ 8  0 10]]


3. Jika banyaknya kolom dari matrix ***A*** adalah sama dengan banyaknya baris matrik ***B***, maka kedua matrik dapat dikalikan dalam bentuk perkalian ***A,B***. Dengan jumlah baris yang mengikuti matriks A dan kolom mengikuti matriks B.

In [5]:
#Cara menentukan ukuran matriks:
#  namamatriks.shape
print(C.shape)

#Cara menentukan jumlah baris:
#  namamatriks.shape[0]
print(C.shape[0])

#Cara menentukan jumlah kolom:
#  namamatriks.shape[1]
print(C.shape[1])

(2, 3)
2
3


In [6]:
print(A*B)

[[  0 -18  32]
 [ -1 -14   2]
 [ 16 -25  21]]


In [7]:
print(A@B)

[[ 26 -52  62]
 [  3 -27  25]
 [ 15 -37  42]]


In [8]:
print(A@C)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

# **Matriks Transpose**
(Baris jadi kolom, dan sebaliknya)
Transpose matriks A......

note : Matriks Covarian adalah matriks awal dikali matriks transposenya.

In [9]:
A_T = A.transpose()
print(A)
print(" ")
print(A_T)

[[0 6 8]
 [1 7 2]
 [4 5 3]]
 
[[0 1 4]
 [6 7 5]
 [8 2 3]]


In [10]:
C_T = C.transpose()
CoV = C*C_T
print(CoV.shape)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [11]:
A = np.array([[10,3,-2],[2,4,-1],[3,-6,8]])
print(A)
print(" ")

A_T = A.transpose()
print(A_T)

[[10  3 -2]
 [ 2  4 -1]
 [ 3 -6  8]]
 
[[10  2  3]
 [ 3  4 -6]
 [-2 -1  8]]


In [12]:
import numpy as np
A = np.array([[1,3,-2],[2,4,-1],[3,-6,8]])
B = np.array([[2,-3,4],[-1,-2,1],[4,-5,7]])
C = np.array([[-2,1,-6],[4,-3,9]])
D = np.array([[2,8,2],[-4,5,6],[7,-3,1]])
t = A*B*D
print(t)
print(" ")
tt = t.transpose()
print(tt)
print(" ")
print(" ")
a = A.transpose()
b = B.transpose()
dd = D.transpose()
print(a*b*dd)
print(" ")
print(" ")
abd = (A+B)*D
ABD = abd.transpose()
print(ABD)
print(" ")
print(" ")
abc = (A+B)*C
ABC = abc.transpose()
print(ABC)

[[  4 -72 -16]
 [  8 -40  -6]
 [ 84 -90  56]]
 
[[  4   8  84]
 [-72 -40 -90]
 [-16  -6  56]]
 
 
[[  4   8  84]
 [-72 -40 -90]
 [-16  -6  56]]
 
 
[[ 6 -4 49]
 [ 0 10 33]
 [ 4  0 15]]
 
 


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

# **Matriks Elementer**

In [13]:
R_3 - 7*R_1

NameError: name 'R_3' is not defined